### ISSUE TITLE
Allow indexing in `ParameterScale`s

### ISSUE THREAD

**Issue by nikhilwoodruff** [openfisca/openfisca-core#1097]
`ParameterScale`s are really useful features, but there is a use case that as far as I know they don't currently support: brackets which differ by a category. For example, taxes in the US use different thresholds by filing status (single, joint, separate, etc.). We'd rather not duplicate the rates, so it'd be great if we could do the following:
```python
scale.calc(income, filer_status_enum_array) -> [values]
```
where the parameter looks like this:
```yaml
brackets:
  - rate:
      2019-01-01: 0.2
    threshold:
      SINGLE:
        2019-01-01: 10_000
      JOINT:
        2019-01-01: 20_000
```

Happy to implement (I think it'd be simple enough, and would be backwards compatible).
