### ISSUE TITLE
Add `label: str` to allowed parameter attributions

### ISSUE THREAD

**Issue by nikhilwoodruff** [openfisca/openfisca-core#1100]
This would serve the UK and US systems, since we're currently providing it via a metadata attribute, but as previously pointed out, it might be more optimal for consistency to add it as a main attribute (since `label` is an attribute of `Variable`). Happy to make the change if this is not objectionable?

cc. @benjello @sandcha

**Comment by sandcha** [comment]
For now the attribute that describes a parameter in a (long) line is the `description` attribute.
It could be renamed into `label` in the futur to have the same name in the model parameters/variables.

[OpenFisca-France is trying this](https://github.com/openfisca/openfisca-france/issues/1672#issuecomment-939986515) for short names:
```yaml
description: label limited to 70 characters
values:
  0001-01-01:
    ...
metadata:
  ux_name: short label  
```

Would this work for you @nikhilwoodruff ?
