### ISSUE TITLE
Ability to test a situation over multiple periods

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#484]
To avoid duplicating test entries like the following ones:
````yaml
- name: "IRPP - Célibataire ayant des revenus salariaux (1AJ) de 20 000 €"
  period: 2010
  absolute_error_margin: 0.5
  input_variables:
    salaire_imposable: 20000
  output_variables:
    irpp: -1181

- name: "IRPP - Célibataire ayant des revenus salariaux (1AJ) de 20 000 €"
  period: 2011
  absolute_error_margin: 0.5
  input_variables:
    salaire_imposable: 20000
  output_variables:
    irpp: -1181
````

It may be useful to be able to write them as follows:

````yaml
 - name: "IRPP - Célibataire ayant des revenus salariaux (1AJ) de 20 000 €"
  periods: 
    - 2010
    - 2011
  absolute_error_margin: 0.5
  input_variables:
    salaire_imposable: 20000
  output_variables:
    irpp: -1181
````
Follows https://github.com/openfisca/openfisca-france/issues/601
