### ISSUE TITLE
Add the possibility to evaluate Range values to calculate parameters using variables

### ISSUE THREAD

**Issue by LorenzoStacchioDev** [openfisca/openfisca-core#657]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Defining a parameter that depends on a variable value. 
This is the **parameter:** 
```
<=70:
description: Threshold within the retirement income is not taxable for people whom has an age major lower than 70  
unit: currency
  values:
    2017-01-01:
      value: 8000.00
70<:
  description: Threshold within the retirement income is not taxable for people whom has an age major than 70
  unit: currency
  values:
    2017-01-01:
      value: 7500.00
``` 
and this is the **variable** containing the formula that use this parameter.
``` 
class threshold_retirement_income_not_taxable(Variable):
    value_type = float
    entity = person
    definition_period = MONTH
    set_input = set_input_divide_by_period 
    label = "Income not taxable depending on person age"
    reference = "..."  

    def formula(person,period,parameters):
        age= person('age',period)
        threshold= parameters(period).taxes.IRPEF.income_not_taxable.threshold_retirement[eta]
        return threshold
``` 

### Here is what I expected to happen:
I expected that, this formula return me the value 8000 for people whom has an age less than 70 and the value 7500 for people whom has an age greater than 70. 

### Here is what actually happened:
This is not supported because **parameters using variables** only supports fixed values and not ranges. 
So this will work if i would write the parameter as follows:
```
70:
description: Threshold within the retirement income is not taxable for people whom has an age equal to 70  
unit: currency
  values:
    2017-01-01:
      value: 8000.00
71:
  description: Threshold within the retirement income is not taxable for people whom has an age equal to 71
  unit: currency
  values:
    2017-01-01:
      value: 7500.00
``` 

### Here is data (or links to it) that can help you reproduce this issue:
This is the test i wrote to use both formula and parameter :
``` 
- name: Test to see the threshold for people based on their age
  period: 2017-01
  input_variables:
    age: 70
  output_variables:
    threshold_retirement_income_not_taxable: 8000
``` 
### Suggestion
I suggest to implement this functionality because some Italian parameters assume values if the variables are smaller or greater than a certain value.

**Comment by benjello** [comment]
This may be useful for France too !

**Comment by guillett** [comment]
I think it would be a great addition too.

However from an implementation point of view, I imagined something similar to marginal rates.

```yaml
description: Retirement income not taxable as a function of the age
steps:
- level:
    2017-01-01:
      value: 8000
  threshold:
    2013-01-01:
      value: 0
- level:
    2017-01-01:
      value: 7500
  threshold:
    2017-01-01:
      value: 70
```
This parameter would also have a `calc` method to get the appropriate level `param.calc(person('age', period))`.

**Comment by benjello** [comment]
One minor point that one should have in mind is that you may have to deal with open/closed range since the law is not always systematic and you may want to stock the value appearing in the legislation.

**Comment by fpagnoux** [comment]
Fun fact, what you suggest @guillett already exists in OpenFisca. The keywords are not `steps` and `level`, but `brackets` and `amount`, but it has been existing since 2014. (It is bugged right now, but the [fix is easy](https://github.com/openfisca/openfisca-core/compare/fix-amount-scale?expand=1)). 

Now, the fact is that no one uses it. Probably mainly because it's never been documented, but I can also see why it's not as convenient/useful as it seems to be.

If I take @LorenzoStacchioDev's example, and put all the logics in the formula, I'd get:

```py
age = person('age', period)
thresolds = parameters(period).taxes.IRPEF.income_not_taxable.threshold_retirement
return where(age <= 70, thresolds.under_70, thresolds.over_70)
```

with  a parameter:

```yaml
over_70:
  2017-01-01: 8000
under_70:
    2017-01-01: 7500
```

The formula is one line more than the first suggestion, reads pretty well, ans is unambiguous. 

If I make `threshold_retirement` a scale, the formula becomes:

```py
age = person('age', period)
thresolds = parameters(period).taxes.IRPEF.income_not_taxable.threshold_retirement
return thresolds.calc(age)
```

and I need to define a scale in the parameters:

```yaml
brackets:
  - amount:
        2017-01-01: 8000
    threshold:
       2017-01-01:  0
  - amount:
        2017-01-01: 7500
    threshold:
       2017-01-01:  70
```

I'm saving a few character in the formula, but
- The formula becomes less explicit. To understand what the formula is doing, I need to:
  - Figure out the nature of `threshold_retirement`
  - Understand the concept of an "fixed amount scale"
  - As @benjello said, there is an ambiguity about 70. The current implementation puts in in the 0-70 bracket, but that's far from obvious. And if I wanted 70 to be in the second bracket, that would not work.
- The parameter is more complex to define

**Comment by fpagnoux** [comment]
Having said that, I don't want to discourage anyone from trying to bring new fancy features to parameters 🙂. 

If someone wants to do so, I'm not sure using the `parameters(period)...threshold_retirement[eta]` notation would be the best thing to do, as 
- `[]`, in many languages (including Python and JS) means accessing an object's property, and I'm not sure it would be straightforward to put complex logics behind it.
- The code between the `[]` notation is some quite complex numpy business, so adapting it to do what you want to do will be tough, at least if you want to enable things like  `parameters(period)...threshold_retirement[eta].some_subparam`. 

But there is another approach that allows experimentation 🙂. You can define a re-usable template function.

Let's keep the parameter file as Lorenzo suggested in the first post:

```yaml
<=70:
description: Threshold within the retirement income is not taxable for people whom has an age major lower than 70  
  values:
    2017-01-01: 8000.00
70<:
  description: Threshold within the retirement income is not taxable for people whom has an age major than 70
  values:
    2017-01-01: 7500.00
```

In a `templates.py` file, you can define templates

```py
def Steps(parameter):
    # Parse the parameter
    def function(array):
        # Apply it to any array
return function
```

And it your variable file:

```
class threshold_retirement_income_not_taxable(Variable):
   ...

    def formula(person,period,parameters):
        age= person('age',period)
        threshold= parameters(period).taxes.IRPEF.income_not_taxable. threshold_retirement 
        return Steps(threshold)(age)  #
```

This approach allows you to develop nice fancy features in your own codebase, avoiding high coupling with core. And such templates could be shared with others, and maybe distributed with core if the community seems it's a good idea. 

Honnestly, if I were to build the marginal scales today, I'd probably use this approach rather than putting them deep in core as they are right now, which often causes trouble 🙂
