### ISSUE TITLE
Round up numbers

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/openfisca-core#699]
Some formula result have too many decimal numbers.
Impact : 
- it does not make sense to have that many decimal when most elements are money in the end.
- it makes mandatory adding a margin of error in most tests.

**Comment by Anna-Livia** [comment]
The `round` branch in  `country_template` contains a failing test because of too many numbers after the decimal point.

Hypotheses : 
1. Results with many numbers after the decimal point are not constant.
2. There is  an existing margin of error in openfisca-run-test
3. outputs given un yaml tests are transformed to contains enough decimal points as to be compared to the result.

**Comment by MattiSG** [comment]
> it does not make sense to have that many decimal when most elements are money in the end.

It sounds reasonable to me to keep as high precision as possible until exporting values. Rounding errors can be quite problematic considering how many times formulas can be chained. Then again, there are already rounding errors…

What about using the `type` property to round to an instance-definable number, for example 3 digits for currency, only when returning values in the final answer (as opposed to “on all intermediary steps”)? 🤔

**Comment by Anna-Livia** [comment]
To give some more information :
The following code : 
``` py
import openfisca_country_template

country = openfisca_country_template
tax_benefit_system = country.CountryTaxBenefitSystem()

scenario = tax_benefit_system.new_scenario().init_from_attributes(
    period='2016-01',
    input_variables={'salary': 1000},
    )

simulation = scenario.new_simulation()

for i in range(100):
    print(simulation.calculate('tax_incentive', period = '2016-01'))
```

Has the following output :
```
[333.33334]
[333.33334]
[333.33334]
[333.33334]
...
```

The folowing test :

```yaml
- name: Someone making 1000 should get a 333 tax incentive
  period: 2016-01
  input_variables:
    salary: 1000
  output_variables:
    tax_incentive:
      2016-01: 333.3333
```

has the following output:
```
AssertionError: b'tax_incentive@2016-01: '[333.33334351] differs from [333.33331299] with an absolute margin [3.05175781e-05] > 0
```

The following tests pass:
```yaml
- name: Someone making 1000 should get a 333 tax incentive
  period: 2016-01
  input_variables:
    salary: 1000
  output_variables:
    tax_incentive:
      2016-01: 333.33334

- name: Someone making 1000 should get a 333 tax incentive
  period: 2016-01
  input_variables:
    salary: 1000
  output_variables:
    tax_incentive:
      2016-01: 333.33333
```
