### ISSUE TITLE
Remove ambiguity from YAML test files

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#808]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
I created test files in YAML in the new format following #716.

Entities are specified as dictionaries and expected values in a sequence.
However, a mapping in YAML is
> an unordered set of key

cf. https://yaml.org/spec/1.2/spec.html#key// and https://yaml.org/spec/1.2/spec.html#id2765608

Therefore it is not possible to create an non-ambiguous test with that snippet:
```yaml
period: 2019-01
input:
  people:
    b:
      salary: 100
    a:
      salary: 200
```

Should expected output be:
```yaml
output:
  salary: [200, 100] # a then b (sorted alphabetically)
```
or
```yaml
output:
  salary: [100, 200] # a then b (as declared in the file)
```

Entity keys are required
```yaml
output:
  salary:
    a: 200
    b: 100
```

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by Morendil** [comment]
There are other options besides specifying entity keys in the output section…
- we could supply an ordering for individuals in the input
- we could sort individuals by string (natural) sort order of their ids

**Comment by guillett** [comment]
I agree with you there are alternatives.

To me:
1. would revert part of #716 and reintroduce more differences with the API payload format (for good reason but still)
2. looks like a hack to me and is not _expected_ by a YAML reader

Whatever the chosen solution, I think this should be considered an relatively urgent issue.

**Comment by Morendil** [comment]
> not expected by a YAML reader

The argument about expectations cuts both ways - if readers' expectations are important and we want to obey the "principle of least surprise" then it *does* make sense to respect insertion order.

Yet another alternative is to represent individuals as a sequence, of course.

> considered an relatively urgent issue

I'm not sure I agree. I'd classify it as more "important" than "urgent". It's probably worth taking more time to think about why we keep bumping into unsatisfactory aspects of how test cases are represented, and what principles we would like to rely on.

For instance, if we want to reliably output helpful messages when we fail to parse a test, then it would be a good idea to adopt the principle that **dictionary keys should come from a fixed set**. This would let us use a schema to validate tests.

However, this would also mean that the representation for input variables should be something like
```
individuals:
  - id: Javier
    variables:
      - name: salary
         period: 2017-01
         value: 3000
```

We are then moving away from a distinct principle (perhaps one that we value without having stated it explicitly), which is that **test data should be as concise as possible**.

I know which one I prefer, and I also fear that if we base decisions like that on personal preference, we can iterate forever without ever settling on a stable choice.

**Comment by guillett** [comment]
Many thanks again @Morendil for your precious insights. The reason why I think it is an urgent issue is the fact that we are relying on PyYAML implementation choices and not YAML specs.

**Comment by fpagnoux** [comment]
Sorry I'm replying very late to this issue, I missed it when it was opened. 

You can write the test in a non-ambiguous way using something like:

```YAML

- name: Income tax for a single parent and a child
  description: Income tax should get properly computed across all members of a household
  period: 2017-01
  input:
    household:
      parents: [ Alicia ]
      children: [ Michael ]
      accommodation_size: 100
      housing_occupancy_status: tenant
    persons:
      Alicia:
        birth: 1961-01-15
        salary:
         2017-01: 2400
      Michael:
        birth: 2002-01-15
        salary:
         2016: 0
  output:
    persons:
      Alicia:
        income_tax: 360
      Michael:
        income_tax: 0
```

(RFC 4 from #716)
