### ISSUE TITLE
Allow composite parameters definition in YAML files

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#853]
Some parameters in the legislation are defined relatively to other parameters in the legislation.
Currently, I do not know how to defined such a _composite_ parameter. Well actually, the current hack is [to create a formula](https://github.com/betagouv/openfisca-bacASable/blob/master/openfisca_bacASable/garantie_jeunes.py#L26-L44) but that's not really pretty.

**Comment by benjello** [comment]
You can use a helper tat depends only on the period or the parameter sub_node tp avoid creating a variable.

**Comment by Morendil** [comment]
@guillett I'm not sure I understand, do you have an example in mind?

**Comment by guillett** [comment]
Thank you both.

@benjello I don't understand your proposal, do you have reference I can have a look at?

@Morendil, I would like [that parameter file (`openfisca_bacASable/parameters/garantie_jeunes.yaml`) in OpenFisca-BacASable](https://github.com/betagouv/openfisca-bacASable/blob/master/openfisca_bacASable/parameters/garantie_jeunes.yaml) to be (or close to):
```yaml
age:
  reference: 'Article L5131-3 du code du travail - https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=DED54A598193DDE1DF59E0AE16BDE87D.tplgfr21s_3?idArticle=LEGIARTI000033023861&cidTexte=LEGITEXT000006072050&dateTexte=20190131'  
  minimum:
    values:
      2009-01-01: 16
  maximum:
    values:
      2009-01-01: 25
montant_maximum:
  values:
    2009-01-01: prestations.minima_sociaux.rsa.montant_de_base_du_rsa * (1 - prestations.minima_sociaux.rsa.forfait_logement.taux_1_personne)
```
