### ISSUE TITLE
RFC: YAML and Web API V2 format

### ISSUE THREAD

**Issue by Morendil** [openfisca/openfisca-core#856]
## RFC closing: May 1

We are currently unable to fulfill our objective of delivering help messages which are Clear, Gentle, Concise, Thorough and Actionable when it comes to YAML tests that do not match the developers' expectations. (This problem affects JSON payloads to a lesser extent, because these are usually programmatically generated.) This is evidenced by the still-open #599 #755 #850 as well as past incidents such as #799 and others.

The problem is that we allow arbitrary key in dictionary structures and place a big burden on the interpreter code to allow flexibility, without spending corresponding effort in anticipating all possible error cases and providing helpful messages. This makes for terse and readable YAML, at the cost of poor discoverability of rules.

This RFC proposes that we *version* both YAML tests and JSON payload formats. Version 1 is to be deprecated on introduction of V2, and removed after 6 months. V1 will still be fully supported in the meantime, but efforts to improve help messages, error handling, robustness etc. will focus on V2.

The characteristic and guiding principle of V2 is that **all keys at every level come from a fixed set**. Anything that changes from test to test, from model to model, extension to extension and so on, is a field value. (Optional keys are OK, as are mutually exclusive keys that allow different structures, such as for single-period values vs multiple-period.)

While we are at it, **the Web API format and the test format become interchangeable**. They must be processed with literally the same code. This means that either:
- **Option 1**, the "output" section of a test case (without values) is now the way requested values are communicated to the Web API, instead of "variables with null values"
- **Option 2**, a test case now looks just like a Web API payload, but instead of "value" it provides a key "expected_value", whereas the Web API payload simply omits the "value" key.

This change accompanies a change of testing strategy where we rely **less on functional tests and more on unit tests**, which in turn relies on substantial improvements to the design of Core classes (Entity, Variable, Simulation). This means that the ability to write concise YAML tests is expected to diminish in value.

However, a `preprocess` field provides a fixed point for flexibility and extensibility. This identifies a module, exporting a Python function `preprocess(input: Dict) -> Dict`. It is the responsibility of this function to turn anything it is given into a valid V2 situation. The names are expected to be descriptive, e.g. "short_format_variables_only" for a preprocessor which takes test in the old-style "variables only" format.

V2 also provides for **both population-oriented and instance-oriented descriptions** of situations, leveraging our recent work with SimulationBuilder for tabular inputs. (Implementation-wise, it is expected that populations will be handled first, allowing for instance-level "adjustments" to be made in a second pass, if the two levels of description coexist.)

**Temporal inferences are requested in the situation description**, rather than set at the variable level. With V2 inputs the variable-level attributes will be ignored, "dispatch" is the default. Ultimately, the goal is to cleanly separate **input handling and validation** from **core computations**.

A representative sample:

```YAML
- version: 2
  preprocess: [preprocessor_module1, preprocessor_module2]
  extensions: []
  reforms: []
  name: Title of the situation
  description: Description of the situation
  # With a reference period here, "period" keys are optional elsewhere
  period: 2015-02
  relative_error_margin: 0.02
  absolute_error_margin: 0.02
  input:
    - instance: individu
      - id: ind1
        variables:
          - name: salary
            period: 2104-12
            value: 1300
          - name: salary
            method: divide
            period: 2105
            value: 16000
          - name: salary
            method: dispatch  
            period: 2106
            value: 1200
          - name: salary
             values:
               - period: 2105-01
                  value: 24000
               - period: 2105-02
                  value: 24000
    - population: individu
      ids: [i1, i2, i3]
      variables:
        - name: salary
           value: [24000, 28000, 12000]
    - population: famille
      members: ["i1,i2", "i3"]
      variables:
        - name: salary
           value: [24000, 28000]
    - instance: famille
      - id: f1
        members:
          - id: i1
            role: parent
        variables:
          - name: loyer
            value: 24000
  output:
    - population: individu
      variables:
        - name: income_tax
          period: 2105-01
          value: [24000, 28000]
        - name: disposable_income
          value: [24000, 28000]
```
