### ISSUE TITLE
Allow arithmetic expression in parameters

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#893]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I used an arithmetic formula in a parameter of a reform:

```
description: "officielle_2018_in_2016"
diesel_2016_2018:
  description: Surcroît de prix du diesel (en euros par hectolitres)
  unit: currency
  values:
    2016-01-01:
      value: 2.6 + 266 * (0.0446 - 0.022)
```

### Here is what I expected to happen:

It would work.

### Here is what actually happened:

```
 openfisca_core.parameters.ParameterParsingError: Error parsing parameter file '/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/reforms/parameters/officielle_2018_in_2016.yaml':
E   Invalid value in officielle_2018_in_2016.diesel_2016_2018[2016-01-01] : 2.6 + 266 * (0.0446 - 0.022)
```

Should we allow for arithmetic expression in parameters ?
