### ISSUE TITLE
Clarify expected behavior for ended variable with value

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#912]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

I got an unexpected result from the following payload (an extract actually)

```yaml---
individus:
  _: {}
familles:
  _:
    ppa_base_ressources_prestations_familiales:
      2019-01: null
    paje_clca:
      2019-01: 120
    parents:
    - _
menages:
  _:
    personne_de_reference:
    - _
```

Where `ppa_base_ressources_prestations_familiales` is a sum of null elements and `paje_clca`  [cf.](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/ppa.py#L280-L313) so I expect `ppa_base_ressources_prestations_familiales` to equal 120.
As `paje_clca` is _ended_ since 2017-04-01 [cf.](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/prestations_familiales/paje.py#L739) then `ppa_base_ressources_prestations_familiales` is equal to 0.

I feel like this is not the less surprising result. I would expect to rely on the provided value or to fail.

What do you think ?

- Developer _(I create tools that use the existing OpenFisca code)_.

Notes:

https://betagouv.github.io/openfisca-tracer/

```json
{
    "individus": {
        "_": {}
    },
    "familles": {
        "_": {
            "ppa_base_ressources_prestations_familiales": {
                "2019-01": null
            },
            "paje_clca": {
                "2019-01": 120
            },
            "parents": [
                "_"
            ]
        }
    },
    "menages": {
        "_": {
            "personne_de_reference": [
                "_"
            ]
        }
    }
}
```
